export const FETCH_CONTACTS_REQUEST = "@contacts/FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_SUCCESS = "@contacts/FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAILURE = "@contacts/FETCH_CONTACTS_FAILURE";

export const FETCH_CONTACT_REQUEST = "@contacts/FETCH_CONTACT_REQUEST";
export const FETCH_CONTACT_SUCCESS = "@contacts/FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_FAILURE = "@contacts/FETCH_CONTACT_FAILURE";

export const CREATE_CONTACT_REQUEST = "@contacts/CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "@contacts/CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAILURE = "@contacts/CREATE_CONTACT_FAILURE";

export const UPDATE_CONTACT_REQUEST = "@contacts/UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "@contacts/UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "@contacts/UPDATE_CONTACT_FAILURE";

export const DELETE_CONTACT_REQUEST = "@contacts/DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "@contacts/DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "@contacts/DELETE_CONTACT_FAILURE";

export const SET_CONTACT = "@contacts/SET_CONTACT";
